AWSTemplateFormatVersion:          '2010-09-09'
Description:                       'Elastic IP for 7 Days to Die'

Resources:
  EIP:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc

Outputs:
  AllocationId:
    Description: Allocation ID of the 7days server Elastic IP
    Value: !GetAtt EIP.AllocationId
    Export:
      Name: Seven-Days-Server-Address
  PublicIp:
    Description: Public IP address of the 7days server Elastic IP
    Value: !Ref EIP
    Export:
      Name: Seven-Days-Server-Address-IP
